name = "InputBuffers"
uuid = "0c81fc1b-5583-44fc-8770-48be1e1cca08"
authors = ["nhz2 <nhz2@cornell.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
